// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtk3s5PXQ4ldLXmsfM70-ipTv1Ys2NdqA',
    appId: '1:1053238718579:android:1b216215867ee574a73a06',
    messagingSenderId: '1053238718579',
    projectId: 'parkinglotdetectionsystem',
    databaseURL: 'https://parkinglotdetectionsystem-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkinglotdetectionsystem.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwYlFmwsm6dUB0mE83D5XsEFx8-K2AJI',
    appId: '1:1053238718579:web:65888bad199678a1a73a06',
    messagingSenderId: '1053238718579',
    projectId: 'parkinglotdetectionsystem',
    authDomain: 'parkinglotdetectionsystem.firebaseapp.com',
    databaseURL: 'https://parkinglotdetectionsystem-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkinglotdetectionsystem.appspot.com',
    measurementId: 'G-T3FQS207CD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Ayo5R9tPTFYbng_zvVrdVNHB-PyjTCI',
    appId: '1:1053238718579:ios:38944ff1fe20a1d6a73a06',
    messagingSenderId: '1053238718579',
    projectId: 'parkinglotdetectionsystem',
    databaseURL: 'https://parkinglotdetectionsystem-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkinglotdetectionsystem.appspot.com',
    iosBundleId: 'com.example.untitled8',
  );

}